### ISSUE TITLE
Vaadin 22 compatibility

### ISSUE THREAD

**Issue by Tonne-TM** [johanneshayry/textfieldformatter#52]
As Vaadin 22 introduced a lot of changes on how a textfield is composed the add-on does not seem to be working correctly anymore.
https://vaadin.com/docs/latest/ds/upgrading/#changes-in-vaadin-22

When you insert numbers they are not automatically formatted anymore. It just looks like a normal textfield.
However loading seems to be working fine. The number is rendered correctly.

Example: Left -> loaded, Right -> typed in
![image](https://user-images.githubusercontent.com/10477806/148679259-ff573d93-89f7-453c-873d-1c3198cac0d9.png)

**Comment by syampillai** [comment]
Yes, not working with Vaadin 22

**Comment by juuso-vaadin** [comment]
Experienced the same issue when testing with V23 pre-release. My error is:
`Uncaught TypeError: Cannot read properties of null (reading 'length') (webpack-internal:///../node_modules/cleave.js/dist/cleave-esm.js:1074:26)`

**Comment by johanneshayry** [comment]
V22 should be fixed in 5.4.0

**Comment by Tonne-TM** [comment]
@johanneshayry  Thanks for fixing (and maintaining) this awesome Vaadin extension. Already deployed the new version. Working like intended again.
